### ISSUE TITLE
[Feature]: Epic: CI/CD & Housekeeping

### ISSUE THREAD

**Issue by kmoberg** [kmoberg/twitter-notifier#9]
### Is your feature request related to an issue? Please describe.

We need a bit of project organization and housekeeping to keep things on track.

### Describe the solution you'd like

- [ ] Add tests for main functions (`lambda_handler`, `get_parameter`, `notify`, `check_entry`)
- [ ] Add CI linting to GitHub workflows
- [ ] Add CI formatting to GitHub workflows
